### ISSUE TITLE
AVR-452 Beyond weapon not adding proficiency

### ISSUE THREAD

**Issue by spamandtuna** [avrae/avrae#896]
**What is the bug?:** Double-Bladed Scimitar attacks are imported without the proficiency bonus.
**Severity:** Medium (minor functional impact)
**Steps to reproduce:**
1. Create a Beyond character proficient with a Double-Bladed Scimitar and equip the weapon (or just use [this one](https://www.dndbeyond.com/characters/17307639)).
2. Import the character with Avrae.
3. Compare the hit bonus in each system.

**Comment by nickcarenza** [comment]
I don't think this is an issue with Avrae because the json api for ddb doesn't  seem to return weapon proficiency. Avrae is using the api endpoint https://www.dndbeyond.com/character/:id/json. I checked https://character-service.dndbeyond.com/character/v3/character/:id as well which the character sheet seems to use and it's not there either as far as i can tell. Am I missing something?
